title: Matt Blackford – Technical Blog
description: Cloud infrastructure, DevOps, and technical leadership writing by Matthew Blackford.
author: Matthew Blackford
theme: jekyll-theme-cayman
markdown: kramdown
baseurl: "/blog"
plugins:
  - jekyll-seo-tag
